version: "3.9"

services:
  api:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    restart: unless-stopped

  web:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: "/api"
    depends_on:
      - api
    ports:
      - "80:80"
    restart: unless-stopped
